version: 2.1

jobs:
  py36_mac:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: "Installing Conda"
          command: |
            curl -o Miniconda3-latest-MacOSX-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
            bash ./Miniconda3-latest-MacOSX-x86_64.sh -b
            ~/miniconda3/bin/conda init bash
      - run:
          name: "Installing VizSeq"
          command: |
            ~/miniconda3/bin/conda create -n vizseq36 python=3.6 -q -y
            ~/miniconda3/bin/conda run -n vizseq36 pip install -e .
            bash get_example_data.sh
      - run:
          no_output_timeout: 60m
          command: ~/miniconda3/bin/conda run -n vizseq36 python -m tests.test_n_gram_based_scorers
      - run:
          no_output_timeout: 60m
          command: ~/miniconda3/bin/conda run -n vizseq36 python -m tests.test_embedding_based_scorers
      - run:
          no_output_timeout: 60m
          command: ~/miniconda3/bin/conda run -n vizseq36 python -m tests.test_ipynb

  py37_mac:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: "Installing Conda"
          command: |
            curl -o Miniconda3-latest-MacOSX-x86_64.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
            bash ./Miniconda3-latest-MacOSX-x86_64.sh -b
            ~/miniconda3/bin/conda init bash
      - run:
          name: "Installing VizSeq"
          command: |
            ~/miniconda3/bin/conda create -n vizseq37 python=3.7 -q -y
            ~/miniconda3/bin/conda run -n vizseq37 pip install -e .
            bash get_example_data.sh
      - run:
          no_output_timeout: 60m
          command: ~/miniconda3/bin/conda run -n vizseq37 python -m tests.test_n_gram_based_scorers
      - run:
          no_output_timeout: 60m
          command: ~/miniconda3/bin/conda run -n vizseq37 python -m tests.test_embedding_based_scorers
      - run:
          no_output_timeout: 60m
          command: ~/miniconda3/bin/conda run -n vizseq37 python -m tests.test_ipynb

  py36_linux:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo apt-get install -y expect
      - run: sudo apt-get install libsndfile1
      - run: sudo pip install -e .
      - run: bash get_example_data.sh
      - run:
          no_output_timeout: 60m
          command: python -m tests.test_n_gram_based_scorers
      - run:
          no_output_timeout: 60m
          command: sudo python -m tests.test_embedding_based_scorers
      - run:
          no_output_timeout: 60m
          command: sudo python -m tests.test_ipynb

  py37_linux:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo apt-get install -y expect
      - run: sudo apt-get install libsndfile1
      - run: sudo pip install -e .
      - run: bash get_example_data.sh
      - run:
          no_output_timeout: 60m
          command: python -m tests.test_n_gram_based_scorers
      - run:
          no_output_timeout: 60m
          command: sudo python -m tests.test_embedding_based_scorers
      - run:
          no_output_timeout: 60m
          command: sudo python -m tests.test_ipynb

workflows:
  version: 2
  build:
    jobs:
      - py36_linux
      - py37_linux
      - py36_mac
      - py37_mac
